Repository Nyam-Crew/server, pull requests merged in 2025-08, with the labels that each got.

#118 feature/#66-teamFeed
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/event/listener/ChallengeClearedListener.java
  everyday/src/main/java/com/nyam/everyday/module/meal/entity/MealLog.java
  everyday/src/main/java/com/nyam/everyday/module/meal/repository/MealLogRepository.java
  everyday/src/main/java/com/nyam/everyday/module/meal/service/MealLogService.java
  everyday/src/main/java/com/nyam/everyday/module/meal/type/MealType.java
  everyday/src/main/java/com/nyam/everyday/module/summary/service/MemberDailySummaryService.java
  everyday/src/main/java/com/nyam/everyday/module/team/enums/ActivityType.java
  everyday/src/main/java/com/nyam/everyday/module/team/enums/MealPeriod.java
  everyday/src/main/java/com/nyam/everyday/module/team/repository/TeamMemberStatusRepository.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamActivityFeedRedisService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamMemberService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamNoticeService.java
  everyday/src/main/java/com/nyam/everyday/module/team/util/FeedIds.java
  everyday/src/main/java/com/nyam/everyday/module/team/view/TeamFeedMessageFormatter.java
  everyday/src/main/java/com/nyam/everyday/web/meal/dto/MealLogResponseDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/controller/TeamActivityFeedController.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamActivityFeedItem.java
Labels: feature

#119 feature/#102-callScoreMethod
  Data/postgresql.schema.init.sql
  everyday/src/main/java/com/nyam/everyday/module/meal/service/MealLogService.java
  everyday/src/main/java/com/nyam/everyday/module/scorelog/entity/ScoreLog.java
  everyday/src/main/java/com/nyam/everyday/module/scorelog/entity/ScoreType.java
  everyday/src/main/java/com/nyam/everyday/module/scorelog/entity/SourceType.java
  everyday/src/main/java/com/nyam/everyday/module/scorelog/repository/ScoreLogRepository.java
  everyday/src/main/java/com/nyam/everyday/module/scorelog/service/MealScoreWriter.java
  everyday/src/main/java/com/nyam/everyday/module/scorelog/service/ScoreAwardService.java
  everyday/src/main/java/com/nyam/everyday/module/scorelog/service/ScoreLogService.java
  everyday/src/main/java/com/nyam/everyday/module/summary/service/MemberDailySummaryService.java
  everyday/src/main/java/com/nyam/everyday/oauth2/OAuth2LoginSuccessHandler.java
Labels: feature

#130 feature/#93-TeamNotification
  everyday/src/main/java/com/nyam/everyday/BackendApplication.java
  everyday/src/main/java/com/nyam/everyday/common/exception/ErrorCode.java
  everyday/src/main/java/com/nyam/everyday/module/chatting/chatmessage/service/ChatMessageService.java
  everyday/src/main/java/com/nyam/everyday/module/chatting/chatroom/registry/ChatRoomRegistry.java
  everyday/src/main/java/com/nyam/everyday/module/meal/service/MealLogService.java
  everyday/src/main/java/com/nyam/everyday/module/notification/service/NotificationService.java
  everyday/src/main/java/com/nyam/everyday/module/notification/service/NotifyToReactService.java
  everyday/src/main/java/com/nyam/everyday/module/summary/service/MemberDailySummaryService.java
  everyday/src/main/java/com/nyam/everyday/module/team/entity/TeamNotification.java
  everyday/src/main/java/com/nyam/everyday/module/team/enums/DeliveryStatus.java
  everyday/src/main/java/com/nyam/everyday/module/team/enums/TeamNotificationType.java
  everyday/src/main/java/com/nyam/everyday/module/team/event/TeamFeedCreatedEvent.java
  everyday/src/main/java/com/nyam/everyday/module/team/repository/TeamMemberStatusRepository.java
  everyday/src/main/java/com/nyam/everyday/module/team/repository/TeamNotificationRepository.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamActivityFeedRedisService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamNoticeService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamNotificationService.java
  everyday/src/main/java/com/nyam/everyday/redis/config/RedisConfig.java
  everyday/src/main/java/com/nyam/everyday/web/chatting/controller/ChatRoomController.java
  everyday/src/main/java/com/nyam/everyday/web/notification/dto/NotifyToReactDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/controller/TeamNotificationController.java
  everyday/src/main/java/com/nyam/everyday/web/team/controller/TestTeamNotificationController.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamNotificationBoxDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamNotificationDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamNotifyDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/mapper/TeamNotificationMapper.java
Labels: feature

#140 Feature/#139 챌린지체커 4종 추가
  Data/postgre.data.init.sql
  everyday/src/main/java/com/nyam/everyday/module/board/repository/BoardRepository.java
  everyday/src/main/java/com/nyam/everyday/module/board/service/BoardService.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/login/Login30DaysChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/meal_log/MealLogFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/post/PostRecipeFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/profile/ProfileCompleteChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/entity/ChallengeCode.java
  everyday/src/main/java/com/nyam/everyday/module/meal/repository/MealLogRepository.java
  everyday/src/main/java/com/nyam/everyday/module/meal/service/MealLogService.java
  everyday/src/main/java/com/nyam/everyday/module/member/service/MemberService.java
  everyday/src/main/java/com/nyam/everyday/module/summary/service/MemberDailySummaryService.java
Labels: feature

#143 Feature/#139 챌린지체커 추가
  everyday/src/main/java/com/nyam/everyday/config/AsyncConfig.java
  everyday/src/main/java/com/nyam/everyday/module/boardComment/repository/BoardCommentRepository.java
  everyday/src/main/java/com/nyam/everyday/module/boardComment/service/BoardCommentService.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/event/listener/ChallengeCheckListener.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/event/listener/ChallengeClearedListener.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/event/listener/MCDCreateListener.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/event/listener/MCDDeleteListener.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/event/listener/ProgressRecomputeListener.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/comment/CommentFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/entity/ChallengeCode.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/repository/MemberChallengeDayRepository.java
Labels: feature

#144 boardCustom 핫픽스
  everyday/src/main/java/com/nyam/everyday/search/board/repository/BoardSearchRepositoryCustom.java
Labels: bug

#145 Refactor/#142 챌린지 체크 리팩토링
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/AbstractChallengeChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/AbstractCountBasedChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/AbstractDateBasedChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/ChallengeChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/CountBasedChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/DateBasedChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/event/listener/ProgressRecomputeListener.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/registry/ChallengeCheckerRegistry.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/comment/CommentFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/like/LikeFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/login/Login30DaysChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/login/LoginFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/meal_log/MealLogFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular/water/WaterFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/comment/CommentFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/like/LikeFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/login/Login30DaysChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/login/LoginFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/meal_log/MealLogFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/post/PostRecipeFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/profile/ProfileCompleteChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/water/Water1L30DaysChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/regular_checker/water/WaterFirstChecker.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/checker/service/ProgressComputeService.java
  everyday/src/main/java/com/nyam/everyday/module/challenge/entity/MemberChallengeStatus.java
Labels: feature

#149 Feature/#148 팀 삭제 시 채팅 삭제하기 위한 메서드 구현
  everyday/src/main/java/com/nyam/everyday/module/chatting/chatmessage/service/ChatMessageService.java
  everyday/src/main/java/com/nyam/everyday/web/test/TestController.java
Labels: feature

#151 feature/#122-frontConnectApi
  everyday/src/main/java/com/nyam/everyday/module/notification/service/NotifyToReactService.java
  everyday/src/main/java/com/nyam/everyday/module/team/entity/TeamActivityFeed.java
  everyday/src/main/java/com/nyam/everyday/module/team/entity/TeamMemberStatus.java
  everyday/src/main/java/com/nyam/everyday/module/team/entity/TeamRankingHistory.java
  everyday/src/main/java/com/nyam/everyday/module/team/repository/TeamActivityFeedRepository.java
  everyday/src/main/java/com/nyam/everyday/module/team/repository/TeamMemberStatusRepository.java
  everyday/src/main/java/com/nyam/everyday/module/team/repository/TeamRankingHistoryRepository.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamActivityFeedRedisService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamActivityFeedService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamMemberService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamNoticeService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamNotificationService.java
  everyday/src/main/java/com/nyam/everyday/module/team/service/TeamService.java
  everyday/src/main/java/com/nyam/everyday/module/team/view/TeamFeedMessageFormatter.java
  everyday/src/main/java/com/nyam/everyday/web/meal/dto/MealLogRequestDto.java
  everyday/src/main/java/com/nyam/everyday/web/member/controller/MemberController.java
  everyday/src/main/java/com/nyam/everyday/web/member/dto/MemberIdResponseDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/controller/TeamActivityFeedController.java
  everyday/src/main/java/com/nyam/everyday/web/team/controller/TeamNotificationController.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamDetailDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamMemberDTO.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamMemberStatusDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamNotificationDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/dto/TeamRankingHistoryDto.java
  everyday/src/main/java/com/nyam/everyday/web/team/mapper/TeamActivityFeedMapper.java
  everyday/src/main/java/com/nyam/everyday/web/team/mapper/TeamMemberStatusMapper.java
  everyday/src/main/java/com/nyam/everyday/web/team/mapper/TeamRankingHistoryMapper.java
Labels: feature

#153 Refactor/#152 채팅 메세지 비동기 처리
  everyday/src/main/java/com/nyam/everyday/config/AsyncConfig.java
  everyday/src/main/java/com/nyam/everyday/module/chatting/chatmessage/service/ChatMessageService.java
  everyday/src/main/java/com/nyam/everyday/web/chatting/controller/ChatMessageController.java
Labels: feature

#154 Refactor/#146 bookmark
  everyday/src/main/java/com/nyam/everyday/module/board/service/BoardService.java
  everyday/src/main/java/com/nyam/everyday/module/boardLike/repository/BoardLikeRepository.java
  everyday/src/main/java/com/nyam/everyday/module/boardLike/service/BoardLikeService.java
  everyday/src/main/java/com/nyam/everyday/module/bookmark/repository/BookmarkRepository.java
  everyday/src/main/java/com/nyam/everyday/module/bookmark/service/BookmarkService.java
  everyday/src/main/java/com/nyam/everyday/search/board/repository/BoardSearchRepositoryImpl.java
  everyday/src/main/java/com/nyam/everyday/search/board/service/BoardIndexEventHandler.java
  everyday/src/main/java/com/nyam/everyday/search/board/service/BoardSearchIndexer.java
  everyday/src/main/java/com/nyam/everyday/web/board/dto/BoardResponseDto.java
  everyday/src/main/java/com/nyam/everyday/web/boardlike/controller/BoardLikeController.java
  everyday/src/main/java/com/nyam/everyday/web/boardlike/dto/LikeStatusResponseDto.java
  everyday/src/main/java/com/nyam/everyday/web/boardlike/dto/ToggleLikeRequestDto.java
  everyday/src/main/java/com/nyam/everyday/web/boardlike/dto/ToggleLikeResponseDto.java
  everyday/src/main/java/com/nyam/everyday/web/bookmark/controller/BookmarkController.java
  everyday/src/main/java/com/nyam/everyday/web/bookmark/dto/ToggleBookmarkRequestDto.java
  everyday/src/main/java/com/nyam/everyday/web/bookmark/dto/ToggleBookmarkResponseDto.java
Labels: Refactor, feature
